# Autogenerated schema
from fastpyxl.typed_serialisable.base import Serialisable
from fastpyxl.typed_serialisable.fields import Field

# could be done using a nestedSequence


class CellWatch(Serialisable):

    tagname = "cellWatch"

    r: str | None = Field.attribute(expected_type=str, allow_none=True)

    def __init__(
        self,
        r=None,
    ):
        self.r = r


class CellWatches(Serialisable):

    tagname = "cellWatches"

    cellWatch: list[CellWatch] = Field.sequence(expected_type=CellWatch, default=list)

    def __init__(
        self,
        cellWatch=(),
    ):
        self.cellWatch = cellWatch
