# Autogenerated schema
from fastpyxl.typed_serialisable.base import Serialisable
from fastpyxl.typed_serialisable.fields import Field

# can be done with a nested sequence


class CustomProperty(Serialisable):

    tagname = "customProperty"

    name: str | None = Field.attribute(expected_type=str, allow_none=True, default=None)

    def __init__(
        self,
        name=None,
    ):
        self.name = name


class CustomProperties(Serialisable):

    tagname = "customProperties"

    customPr: list[CustomProperty] = Field.sequence(expected_type=CustomProperty, default=list)

    def __init__(
        self,
        customPr=(),
    ):
        self.customPr = list(customPr)
