# Autogenerated schema
from fastpyxl.typed_serialisable.base import Serialisable
from fastpyxl.typed_serialisable.fields import Field


class Extension(Serialisable):

    tagname = "extension"

    uri: str | None = Field.attribute(expected_type=str, allow_none=True)

    def __init__(
        self,
        uri=None,
    ):
        self.uri = uri


class ExtensionList(Serialisable):

    tagname = "extensionList"

    ext: list[Extension] = Field.sequence(expected_type=Extension, default=list)

    def __init__(
        self,
        ext=(),
    ):
        self.ext = ext


class IgnoredError(Serialisable):

    tagname = "ignoredError"

    sqref: str | None = Field.attribute(expected_type=str, allow_none=True)
    evalError: bool | None = Field.attribute(expected_type=bool, allow_none=True)
    twoDigitTextYear: bool | None = Field.attribute(expected_type=bool, allow_none=True)
    numberStoredAsText: bool | None = Field.attribute(expected_type=bool, allow_none=True)
    formula: bool | None = Field.attribute(expected_type=bool, allow_none=True)
    formulaRange: bool | None = Field.attribute(expected_type=bool, allow_none=True)
    unlockedFormula: bool | None = Field.attribute(expected_type=bool, allow_none=True)
    emptyCellReference: bool | None = Field.attribute(expected_type=bool, allow_none=True)
    listDataValidation: bool | None = Field.attribute(expected_type=bool, allow_none=True)
    calculatedColumn: bool | None = Field.attribute(expected_type=bool, allow_none=True)

    def __init__(
        self,
        sqref=None,
        evalError=False,
        twoDigitTextYear=False,
        numberStoredAsText=False,
        formula=False,
        formulaRange=False,
        unlockedFormula=False,
        emptyCellReference=False,
        listDataValidation=False,
        calculatedColumn=False,
    ):
        self.sqref = sqref
        self.evalError = evalError
        self.twoDigitTextYear = twoDigitTextYear
        self.numberStoredAsText = numberStoredAsText
        self.formula = formula
        self.formulaRange = formulaRange
        self.unlockedFormula = unlockedFormula
        self.emptyCellReference = emptyCellReference
        self.listDataValidation = listDataValidation
        self.calculatedColumn = calculatedColumn


class IgnoredErrors(Serialisable):

    tagname = "ignoredErrors"

    ignoredError: list[IgnoredError] = Field.sequence(expected_type=IgnoredError, default=list)
    extLst: ExtensionList | None = Field.element(expected_type=ExtensionList, allow_none=True)

    xml_order = ("ignoredError", "extLst")

    def __init__(
        self,
        ignoredError=(),
        extLst=None,
    ):
        self.ignoredError = ignoredError
        self.extLst = extLst
