# Autogenerated schema
from fastpyxl.typed_serialisable.base import Serialisable
from fastpyxl.typed_serialisable.fields import Field


class CellSmartTagPr(Serialisable):

    tagname = "cellSmartTagPr"

    key: str | None = Field.attribute(expected_type=str, allow_none=True)
    val: str | None = Field.attribute(expected_type=str, allow_none=True)

    def __init__(
        self,
        key=None,
        val=None,
    ):
        self.key = key
        self.val = val


class CellSmartTag(Serialisable):

    tagname = "cellSmartTag"

    cellSmartTagPr: list[CellSmartTagPr] = Field.sequence(
        expected_type=CellSmartTagPr, default=list
    )
    type: int | None = Field.attribute(expected_type=int, allow_none=True)
    deleted: bool | None = Field.attribute(expected_type=bool, allow_none=True)
    xmlBased: bool | None = Field.attribute(expected_type=bool, allow_none=True)

    xml_order = ("cellSmartTagPr",)

    def __init__(
        self,
        cellSmartTagPr=(),
        type=None,
        deleted=False,
        xmlBased=False,
    ):
        self.cellSmartTagPr = list(cellSmartTagPr)
        self.type = type
        self.deleted = deleted
        self.xmlBased = xmlBased


class CellSmartTags(Serialisable):

    tagname = "cellSmartTags"

    cellSmartTag: list[CellSmartTag] = Field.sequence(
        expected_type=CellSmartTag, default=list
    )
    r: str | None = Field.attribute(expected_type=str, allow_none=True)

    xml_order = ("cellSmartTag",)

    def __init__(
        self,
        cellSmartTag=(),
        r=None,
    ):
        self.cellSmartTag = list(cellSmartTag)
        self.r = r


class SmartTags(Serialisable):

    tagname = "smartTags"

    cellSmartTags: list[CellSmartTags] = Field.sequence(
        expected_type=CellSmartTags, default=list
    )

    xml_order = ("cellSmartTags",)

    def __init__(
        self,
        cellSmartTags=(),
    ):
        self.cellSmartTags = list(cellSmartTags)
